### ISSUE TITLE
[feature request] Retry download/continue where left off 

### ISSUE THREAD

**Issue by RonStrauss** [M4p4/EromeDownloader#3]
Currently, downloads can finish early, and then the file is incomplete. (despite having the right duration metadata)

Is there a way to circumvent this? Any idea how to check for this incompleteness? i tried running `ffmpeg -v error` but nothing came up on these files.

**Comment by RonStrauss** [comment]
I've written the following code, it uses `cv2`. 
Seems to be working well. The only problem is, ffmpeg keep emitting the errors. I tried some methods online to silence ffmpeg but couldn't get it to work.

The only way I can see making it work, is either trying all online methods, or prefixing the final list print with a special character, and then keep retrying until the list returns empty.

Would love your input on this, @M4p4.

```python
import os
import argparse
import sys
import cv2

def is_mp4_complete(filepath):
    try:
        cap = cv2.VideoCapture(filepath)
        if not cap.isOpened():
            print(f"{filepath}: Cannot open file for playback.")
            return filepath

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames == 0:
            print(f"{filepath}: No frames found.")
            return filepath

        # Try seeking to the last 10 frames
        last_frames = 10
        end_frame = total_frames - last_frames if total_frames > last_frames else 0
        cap.set(cv2.CAP_PROP_POS_FRAMES, end_frame)
        ret, frame = cap.read()

        if ret is False:
            return filepath

    except Exception as e:
        return filepath
    finally:
        cap.release()

def check_mp4_files(directory):
   invalid_files = [filename for filename in os.listdir(directory) if filename.endswith('.mp4') and is_mp4_complete(os.path.join(directory, filename)) is not None]
   print(f"Invalid files: {invalid_files}")



if __name__ == "__main__":
    parser = argparse.ArgumentParser(sys.argv[1:])
    parser.add_argument("-f", help="folder to check", type=str, required=True)
    args = parser.parse_args()
    check_mp4_files(os.path.join("downloads",args.f))

```

**Comment by M4p4** [comment]
Hi, this not a good solution can you provide me please a example url, so i can reproduce the problem. Thanks

**Comment by RonStrauss** [comment]
Thanks for replying!
My apologies, I thought this was a known issue, it seemed to happen to me frequently.
After a few hours, I ran into the problem again:
![image](https://github.com/user-attachments/assets/8d983f0b-9557-4f34-85e6-ba0b46782302)
