### ISSUE TITLE
Timeout after 5 minutes

### ISSUE THREAD

**Issue by berror88** [M4p4/EromeDownloader#6]
Hello,
with larger files I get a timeout error if they don't get downloaded in 5 minutes. 
Reading the documentation for asyncio it says: "The executor is given a timeout duration of 5 minutes to shutdown." ([LINK](https://docs.python.org/3/library/asyncio-runner.html#asyncio.run))

I tried changing the values in the asyncio library.

Specifically in:
Constants.py
runners.py
streams.py

No luck.

I hope that that you have a greater understanding of the library to add an argument where you can manually put the timeout value in seconds. (with -u and -c maybe add -t where -t is the file timeout value)
If not, I'll try to modify the code myself but that will require some time to learn the library.

**Comment by berror88** [comment]
Fixed it.
Value for the default timeout is located in the aiohttp/client.py (line 209)

**Comment by M4p4** [comment]
@berror88 Fixed it and also 2 other bugs. Thanks for reporting wish you a great week.
